export default {
  GET_USERS_REQUESTED: 'GET_USERS_REQUESTED',
  GET_USERS_RECEIVED: 'GET_USERS_RECEIVED',
  GET_USERS_FAILED: 'GET_USERS_FAILED',
  LOGIN_REQUESTED: 'LOGIN_REQUESTED',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILED: 'LOGIN_FAILED',
};
